import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { basename, dirname, extname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import matter from "gray-matter";

const appRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const timestamp = "2026-07-17T00:00:00.000Z";
const settingFiles = new Map([
  ["profile", "profile.json"],
  ["navigation", "navigation.json"],
  ["homepage", "homepage.json"],
  ["about", "about.json"],
  ["guestbook", "guestbook.json"],
  ["now_page", "now.json"],
  ["credits", "credits.json"],
  ["page_copy", "page-copy.json"],
  ["artwork", "artwork.json"],
]);

function readJson(filename) {
  return JSON.parse(readFileSync(join(appRoot, "src", "data", filename), "utf8"));
}

function sql(value) {
  if (value === null || value === undefined) return "NULL";
  if (typeof value === "number") return String(value);
  return `'${String(value).replaceAll("'", "''")}'`;
}

function json(value) {
  return sql(JSON.stringify(value));
}

function dateText(value) {
  const date = value instanceof Date ? value : new Date(String(value));
  if (Number.isNaN(date.getTime())) throw new Error(`Invalid content date: ${String(value)}`);
  return date.toISOString();
}

function optionalText(value) {
  const normalized = typeof value === "string" ? value.trim() : "";
  return normalized || null;
}

function taxonomySlug(value) {
  return value
    .normalize("NFKC")
    .replace(/[A-Z]/g, (character) => character.toLowerCase())
    .replace(/[\p{P}\s]+/gu, "-")
    .replace(/^-+|-+$/g, "");
}

function markdownFiles(directory) {
  return readdirSync(directory)
    .filter((filename) => [".md", ".markdown"].includes(extname(filename).toLowerCase()))
    .sort();
}

function insert(table, columns, values) {
  return `INSERT INTO ${table} (${columns.join(", ")}) VALUES (${values.map(sql).join(", ")});`;
}

export function generateD1Seed() {
  const lines = [
    "-- Generated by scripts/generate-d1-seed.mjs. Do not edit manually.",
    "-- seed-setting-profile",
    "",
  ];

  for (const [key, filename] of settingFiles) {
    lines.push(insert("site_settings", ["key", "value_json", "updated_at"], [
      key, JSON.stringify(readJson(filename)), timestamp,
    ]));
  }

  const taxonomy = readJson("taxonomy.json");
  taxonomy.categories.forEach((category, index) => {
    lines.push(insert("categories", ["id", "name", "slug", "description", "sort_order", "enabled"], [
      `seed-category-${index + 1}`, category.name, taxonomySlug(category.name),
      optionalText(category.description), index, 1,
    ]));
  });

  const friendSource = readJson("friends.json");
  const { links, ...friendPage } = friendSource;
  lines.push(insert("friend_page", ["id", "value_json", "updated_at"], [
    1, JSON.stringify(friendPage), timestamp,
  ]));
  links.forEach((friend, index) => {
    lines.push(insert("friends", [
      "id", "name", "url", "description", "interests_json", "sort_order", "enabled", "updated_at",
    ], [
      `seed-friend-${index + 1}`, friend.name, friend.url, friend.description,
      JSON.stringify(friend.interests), index, 1, timestamp,
    ]));
  });

  const postsRoot = join(appRoot, "src", "content", "posts");
  for (const filename of markdownFiles(postsRoot)) {
    const parsed = matter(readFileSync(join(postsRoot, filename), "utf8"));
    const slug = basename(filename, extname(filename));
    lines.push(insert("posts", [
      "id", "slug", "title", "description", "body", "published_at", "updated_at", "draft",
      "category", "tags_json", "cover", "cover_alt", "featured", "series", "canonical_url",
    ], [
      `seed-post-${slug}`, slug, String(parsed.data.title), String(parsed.data.description), parsed.content,
      dateText(parsed.data.publishedAt), parsed.data.updatedAt ? dateText(parsed.data.updatedAt) : null,
      parsed.data.draft ? 1 : 0, String(parsed.data.category), JSON.stringify(parsed.data.tags ?? []),
      optionalText(parsed.data.cover), optionalText(parsed.data.coverAlt), parsed.data.featured ? 1 : 0,
      optionalText(parsed.data.series), optionalText(parsed.data.canonicalUrl),
    ]));
  }

  const projectsRoot = join(appRoot, "src", "content", "projects");
  markdownFiles(projectsRoot).forEach((filename, index) => {
    const parsed = matter(readFileSync(join(projectsRoot, filename), "utf8"));
    const slug = basename(filename, extname(filename));
    lines.push(insert("projects", [
      "id", "slug", "title", "description", "body", "project_date", "status", "tags_json",
      "cover", "repository_url", "demo_url", "featured", "sort_order",
    ], [
      `seed-project-${slug}`, slug, String(parsed.data.title), String(parsed.data.description), parsed.content,
      dateText(parsed.data.date), String(parsed.data.status), JSON.stringify(parsed.data.tags ?? []),
      optionalText(parsed.data.cover), optionalText(parsed.data.repositoryUrl), optionalText(parsed.data.demoUrl),
      parsed.data.featured ? 1 : 0, index,
    ]));
  });

  return `${lines.join("\n")}\n`;
}

const output = join(appRoot, "migrations", "0002_seed.sql");
writeFileSync(output, generateD1Seed(), "utf8");
console.log(`Wrote ${output}`);
