-- Generated by scripts/generate-d1-seed.mjs. Do not edit manually.
-- seed-setting-profile

INSERT INTO site_settings (key, value_json, updated_at) VALUES ('profile', '{"name":"233昭","siteTitle":"代码与生活碎片","description":"记录动画、开发与日常灵感的个人博客。","bio":"在代码与海风之间记录生活。","avatar":"/src/assets/profile/b_661194cb40c25792a896f0450f4e2736.jpg","occupation":"","location":"","motto":"","email":"","website":""}', '2026-07-17T00:00:00.000Z');
INSERT INTO site_settings (key, value_json, updated_at) VALUES ('navigation', '{"items":[{"label":"首页","href":"/"},{"label":"文章","href":"/posts/"},{"label":"分类","href":"/categories/"},{"label":"归档","href":"/archive/"},{"label":"项目","href":"/projects/"},{"label":"友链","href":"/friends/"},{"label":"关于","href":"/about/"},{"label":"留言","href":"/guestbook/"}],"mobile":{"kicker":"Navigation","title":"去往哪里？","searchLabel":"搜索站内内容","note":"动画、代码与生活碎片，在海风里慢慢更新。"},"footer":{"navigationLabel":"Explore","linksLabel":"Elsewhere","rssLabel":"RSS 订阅","creditsLabel":"作品与鸣谢","note":"Astro SSR · Made beside the sea."}}', '2026-07-17T00:00:00.000Z');
INSERT INTO site_settings (key, value_json, updated_at) VALUES ('homepage', '{"hero":{"eyebrow":"Personal notes · 2026","typingLabel":"此刻记录","typingPhrases":["七月动画里的海风","Astro 与温柔的界面","平凡日子里的微光"],"primaryActionLabel":"开始阅读","secondaryActionLabel":"认识 233昭","scrollLabel":"向下阅读"},"status":{"label":"站点状态","message":"安静运行中","postsLabel":"文章","topicsLabel":"主题","latestLabel":"最近更新"},"featuredPosts":{"eyebrow":"Featured stories","title":"最近，写下这些","linkLabel":"浏览全部文章","emptyMessage":"第一篇故事正在路上。"},"topics":{"eyebrow":"Browse by feeling","title":"从一个主题出发","navigationLabel":"文章分类捷径"},"featuredProjects":{"eyebrow":"Selected works","title":"正在搭建的小世界","description":"把兴趣变成可以慢慢迭代、也可以随时回看的东西。","detailLabel":"查看项目","allLabel":"全部项目","statusLabels":{"active":"进行中","completed":"已完成","archived":"已归档"}},"introduction":{"eyebrow":"A little about me","title":"在喜欢的事物之间，慢慢生活。","body":"这里收集动画留下的回声、开发过程中的小发现，也收藏光线、海风和寻常周末。不是急着给生活下结论，只想把值得回看的瞬间认真放好。","primaryActionLabel":"更多关于我","secondaryActionLabel":"来留言","artworkCaption":"Summer dream"}}', '2026-07-17T00:00:00.000Z');
INSERT INTO site_settings (key, value_json, updated_at) VALUES ('about', '{"seoDescription":"个人介绍、兴趣、工具与站点时间线。","hero":{"eyebrow":"Hello, here is","introduction":"我把这里当作一间靠近海风的网络小屋：动画负责留下想象，代码负责搭好书架，日常则慢慢填满其中的空隙。写作不追赶热闹，只记录愿意再次回看的东西。","guestbookLabel":"在留言簿打招呼","rssLabel":"RSS 订阅"},"interests":{"eyebrow":"Interests · 喜欢的事","title":"在几条不同的路上，寻找相似的光","description":"兴趣不需要被整理成履历，它们更像长期陪伴写作的坐标。","items":[{"title":"动画与声音","description":"记录镜头、配乐和片尾之后仍然留下的情绪。"},{"title":"前端与写作","description":"把结构、可访问性与内容维护做成安静可靠的网页。"},{"title":"光影与日常","description":"收藏季节颜色、街角光线和不需要解释的小片段。"},{"title":"阅读与摘录","description":"用自己的问题回访长文，而不是只保存漂亮句子。"}]},"workbench":{"eyebrow":"Workbench · 常用工具","title":"轻量、可读，也方便明天继续整理","description":"工具的价值在于减少写作和维护之间的摩擦。这个站点使用 Astro SSR、运行时内容校验与少量浏览器脚本，让后台保存后的内容无需重建即可更新。","tools":["Astro","TypeScript","原生 CSS","Markdown","Content Collections","Playwright"]},"timeline":{"eyebrow":"Timeline · 小站时间线","title":"从第一块空白画布开始","description":"从 2026 年 7 月 15 日开始，记录这间小屋从页面雏形到数据库后台的真实开发过程。","entries":[{"date":"2026-07-15","title":"开始搭建个人博客","description":"创建 Astro 项目，确定 233昭 的站点身份与个人博客的基础页面结构。"},{"date":"2026-07-15","title":"确定二次元视觉方向","description":"加入首页人物主视觉、头像、动画交互，并持续调整人物构图与页面比例。"},{"date":"2026-07-16","title":"接入 SQLite 内容后台","description":"将文章、项目、分类、页面设置和友链迁移到统一数据库与单管理员后台。"},{"date":"2026-07-16","title":"开放友链与数据库留言","description":"完成友链增删改与排序，并加入访客留言提交、审核、公开和删除流程。"}]}}', '2026-07-17T00:00:00.000Z');
INSERT INTO site_settings (key, value_json, updated_at) VALUES ('guestbook', '{"seoDescription":"留下一句话、一个问题，或一段路过这里的心情。","hero":{"badge":"留言簿","eyebrow":"Guestbook · 留下回声","title":"留言簿","description":"如果一篇文章让你想起了什么，或只是想说一声“来过”，都可以把话留在这里。留言保存到本站数据库，审核后会公开显示。"},"guidelines":{"eyebrow":"Before writing","title":"写之前的小约定","items":["尊重彼此，不发布私人信息、广告或攻击性内容。","谈论文章时可以直接贴链接，方便后来者理解上下文。","留言提交后进入审核队列，邮箱仅用于博主联系，不会公开显示。"],"setupLabel":"开始写留言"},"discussion":{"eyebrow":"Leave a note","title":"把想说的话留在这里","description":"无需第三方账号。提交后的留言会进入后台审核，通过后展示在下方。"}}', '2026-07-17T00:00:00.000Z');
INSERT INTO site_settings (key, value_json, updated_at) VALUES ('credits', '{"title":"作品与鸣谢","description":"查看本站插画来源、开源依赖与讨论区配置说明。","hero":{"eyebrow":"Credits · 来源与感谢","heading":"认真记录每一束照进本站的光","introduction":"插画、开源工具与社区服务共同构成这间网络小屋。这里保留可核对的来源、用途和配置入口，方便后来维护与替换。"},"artwork":{"eyebrow":"Artwork · 画面来源","heading":"本站使用的素材记录","introduction":"页面只使用下列已确认素材；展示位置与替代文字一并记录。","sourceLinkLabel":"在原始页面中查看来源"},"libraries":{"eyebrow":"Open source · 开源工具","heading":"站点建立在这些项目之上","linkLabel":"项目主页","items":[{"name":"Astro","role":"服务端渲染与页面框架","license":"MIT","url":"https://github.com/withastro/astro"},{"name":"Lucide","role":"界面图标","license":"ISC","url":"https://github.com/lucide-icons/lucide"},{"name":"Marked","role":"运行时 Markdown 渲染","license":"MIT","url":"https://github.com/markedjs/marked"},{"name":"Giscus","role":"基于 Discussions 的留言与评论","license":"MIT","url":"https://github.com/giscus/giscus"}]}}', '2026-07-17T00:00:00.000Z');
INSERT INTO site_settings (key, value_json, updated_at) VALUES ('page_copy', '{"posts":{"title":"文章","description":"浏览全部公开文章。","eyebrow":"Writing index · 文章索引","heading":"所有文章","introduction":"把动画片段、开发笔记与生活里的微光，按时间轻轻收在这里。","emptyTitle":"新的文字正在路上","emptyDescription":"这里暂时还没有公开文章，过一会儿再来看看吧。"},"archive":{"title":"文章归档","description":"按年份与月份浏览全部公开文章。","eyebrow":"Chronicle · 时间归档","heading":"写下的日子，沿时间展开","emptyTitle":"时间线上还没有文章","emptyDescription":"第一篇公开文章发布后，会自动出现在对应月份。"},"categories":{"title":"文章分类","description":"从主要主题进入文章。","eyebrow":"Filed by subject · 分类","heading":"从一个主题开始阅读","introduction":"每篇文章只归入一个主要分类。像沿着书架上的隔板，先选择今天想靠近的方向。","emptyTitle":"分类书架还是空的","emptyDescription":"公开文章出现后，主题入口会自动整理在这里。"},"tags":{"title":"文章标签","description":"用标签交叉浏览文章。","eyebrow":"Small constellations · 标签","heading":"沿着关键词遇见文章","introduction":"标签像文章之间细小的连线。字号只表示出现频率，不代表重要程度。","emptyTitle":"还没有可以展开的标签","emptyDescription":"公开文章出现后，关键词会自动汇集在这里。"},"projects":{"title":"项目","description":"浏览正在推进、已经完成与收进档案的项目记录。","eyebrow":"Projects · 小型世界","heading":"把兴趣做成可以继续生长的东西","introduction":"开发实验、内容整理与视觉笔记。每个项目都保留真实状态，外部链接只在确实配置后出现。","emptyTitle":"项目架上还是空的","emptyDescription":"新的实验整理好后，会从这里开始记录。","filteredEmptyTitle":"这个状态下还没有项目","filteredEmptyDescription":"换一个状态看看，或稍后再来。"},"search":{"title":"搜索","description":"搜索文章正文，并按分类或多个标签筛选结果。","eyebrow":"Search · 搜索","heading":"从文字里，找回一条线索","introduction":"搜索标题与正文，分类为精确匹配；同时勾选多个标签时，会显示符合其中任意一个标签的文章。"},"notFound":{"title":"404 · 页面没有找到","description":"请求的页面没有找到，可以返回首页、搜索文章或浏览最近更新。","eyebrow":"Lost at sea · 航线偏移","heading":"这片海域暂时没有页面","introduction":"链接可能已经移动，也可能只是多拐了一个弯。可以回到首页重新出发，或直接搜索想找的文章。","homeLabel":"返回首页","searchLabel":"搜索文章","recentEyebrow":"Recent notes","recentTitle":"最近写下"}}', '2026-07-17T00:00:00.000Z');
INSERT INTO site_settings (key, value_json, updated_at) VALUES ('artwork', '{"homeHero":{"image":"/src/assets/backgrounds/home-hero.png","title":"233昭首页主视觉","alt":"粉蓝海浪间微笑的白发少女插画"},"aboutSummerDream":{"image":"/src/assets/backgrounds/about-summer-dream.jpg","title":"【动态壁纸】夏日白色绮梦","alt":"粉紫色海边的白发少女插画","sourceUrl":"https://www.bilibili.com/video/BV1NCjx6oEhj/","uploader":"清水未萌_Minamo","bvid":"BV1NCjx6oEhj"}}', '2026-07-17T00:00:00.000Z');
INSERT INTO categories (id, name, slug, description, sort_order, enabled) VALUES ('seed-category-1', '开发', '开发', 'Astro、前端工程与代码实践。', 0, 1);
INSERT INTO categories (id, name, slug, description, sort_order, enabled) VALUES ('seed-category-2', '阅读', '阅读', '长文、书籍与个人摘录工作流。', 1, 1);
INSERT INTO categories (id, name, slug, description, sort_order, enabled) VALUES ('seed-category-3', '生活', '生活', '日常光影、音乐与生活片段。', 2, 1);
INSERT INTO friend_page (id, value_json, updated_at) VALUES (1, '{"seoDescription":"一些关于动画、开发、阅读与生活的友好站点。","hero":{"eyebrow":"Friends · 沿途相遇","title":"把彼此的小站，连成一张安静的地图","description":"友链不是数字交换，而是对另一处长期写作空间的认真介绍。这里保存愿意长期往来的站点。"},"noticeTitle":"友链说明","notice":"以下友链为演示数据，域名均使用 .example，不指向真实站点。","visitLabel":"访问站点","emptyTitle":"友链册还没有条目","emptyDescription":"遇见长期写作的邻居后，这里会出现第一张名片。","invitation":{"eyebrow":"A small note","title":"未来想交换友链？","description":"可以先在留言簿介绍站点名称、地址与主要写作主题。正式展示前会确认链接可访问、说明准确，并用清楚的外链标识告知访客。","actionLabel":"去留言簿"}}', '2026-07-17T00:00:00.000Z');
INSERT INTO friends (id, name, url, description, interests_json, sort_order, enabled, updated_at) VALUES ('seed-friend-1', '春潮放映室', 'https://spring-screen.example/', '记录动画分镜、配乐与片尾余韵的虚构小站。', '["动画","音乐"]', 0, 1, '2026-07-17T00:00:00.000Z');
INSERT INTO friends (id, name, url, description, interests_json, sort_order, enabled, updated_at) VALUES ('seed-friend-2', '白昼代码簿', 'https://daylight-code.example/', '整理前端实验和阅读笔记的虚构开发日志。', '["前端","开源"]', 1, 1, '2026-07-17T00:00:00.000Z');
INSERT INTO friends (id, name, url, description, interests_json, sort_order, enabled, updated_at) VALUES ('seed-friend-3', '纸上星图', 'https://paper-stars.example/', '分享小说、散文与夜间观察的虚构文字空间。', '["阅读","随笔"]', 2, 1, '2026-07-17T00:00:00.000Z');
INSERT INTO friends (id, name, url, description, interests_json, sort_order, enabled, updated_at) VALUES ('seed-friend-4', '风铃照片馆', 'https://windbell-photo.example/', '收集街角光影和季节颜色的虚构摄影册。', '["摄影","生活"]', 3, 1, '2026-07-17T00:00:00.000Z');
INSERT INTO posts (id, slug, title, description, body, published_at, updated_at, draft, category, tags_json, cover, cover_alt, featured, series, canonical_url) VALUES ('seed-post-astro-content-collections', 'astro-content-collections', '用 Astro Content Collections 整理个人写作', '从字段约束、稳定路径到构建校验，记录一次小型 Astro 内容系统的整理过程。', '
个人博客写久以后，最先变乱的往往不是样式，而是内容：日期有几种写法，标签大小写不一致，封面有时忘记替代文字。Astro 的 Content Collections 适合把这些约定放进代码，让 Markdown 继续保持轻便，同时在构建阶段尽早暴露问题。下面的字段与文章只是本站的**演示样例**，用于说明方法，并不代表一套必须照搬的生产配置。

## 先把约定写成结构

我只保留页面真正会使用的字段，并让必填项保持少而清楚：

- `title` 与 `description` 服务列表页和搜索结果；
- `publishedAt` 决定归档与排序，`draft` 控制发布状态；
- `category` 只选一个，`tags` 用来描述多个侧面；
- 封面可选，但一旦提供，就必须同时写出有意义的替代文字。

一个精简的示意 schema 可以这样写：

```ts
const post = z.object({
  title: z.string().trim().min(1),
  publishedAt: z.coerce.date(),
  draft: z.boolean().default(false),
  tags: z.array(z.string()).min(1).max(8),
  category: z.string().trim().min(1),
});
```

## 让文件路径承担身份

文章文件名就是稳定 slug，例如 `astro-content-collections.md` 对应固定详情路径。标题可以微调，链接却不会跟着漂移。分类页、标签页和年份归档都从同一份集合数据派生，不再维护容易过期的手写索引。具体加载方式可参考 [Astro Content Collections 文档](https://docs.astro.build/zh-cn/guides/content-collections/)。

## 把错误留在发布之前

现在每次提交前，我会依次检查三件事：schema 是否通过、草稿是否被过滤、文章链接是否能由 slug 找到。标签还会先做 Unicode 规范化再去重，避免全角字符或多余空格制造两个看似相同的入口。

我也刻意不在 frontmatter 里保存阅读时长、相关文章或归档月份。这些信息都能从正文、分类和发布日期计算出来；重复写入只会让作者在修改后多一处需要同步。内容文件负责表达事实，派生数据交给统一函数生成，边界因此更容易理解和测试。

这种整理不会替作者决定写什么，却能减少写作之外的犹豫。新建文章时，我只需复制一份最小 frontmatter，剩下的排序、聚合与校验交给构建流程。工具安静地守住边界，正文才有更多空间留给真正想说的话。
', '2026-07-12T00:00:00.000Z', NULL, 0, '开发', '["Astro","TypeScript","内容管理"]', NULL, NULL, 1, '博客开发笔记', NULL);
INSERT INTO posts (id, slug, title, description, body, published_at, updated_at, draft, category, tags_json, cover, cover_alt, featured, series, canonical_url) VALUES ('seed-post-blog-design-log', 'blog-design-log', '这间网络小屋的设计记录', '记录 233昭 的博客从内容优先、视觉留白到移动端与深色主题的设计取舍。', '
我把个人博客想成一间可以反复整理的网络小屋：门口要容易找到，书架要能继续增加，窗外的风景很好看，但不能挡住阅读。233昭 的文章和项目包含可替换的**演示资料**；这篇记录描述的是样例站点的设计过程，不暗示未经说明的私人经历。

## 从内容而不是卡片开始

最初草图塞满了圆角卡片：简介一张、标签一张、时间线又一张。信息看似整齐，页面却像许多互不相干的小盒子。后来我只为重复出现的文章与项目保留卡片，其余部分改成全宽区段，用留白、细线和标题层级建立节奏。正文宽度限制在适合中文阅读的范围，长标题允许自然换行，不通过缩小字号勉强塞进一行。

视觉上以白色与炭黑为基础，海青和樱粉只负责强调。这样既保留轻盈的动画气质，也避免整个界面被单一色相淹没。圆角、阴影和边框各自只有少量规格，新增组件时先复用，而不是继续发明例外。

## 同一幅图，两种构图

桌面首屏利用插画左侧留白叠放标题，前景图保持完整比例；移动端则把图像和文字拆成上下两段，避免文字压住人物。关键规则可以浓缩为：

```css
.hero-art { object-fit: contain; }

@media (max-width: 899px) {
  .hero { grid-template-columns: 1fr; }
  .hero-copy { order: 2; }
}
```

为减少布局跳动，图片容器预先声明宽高比，卡片网格也使用稳定的列定义。关于不同尺寸资源的选择，我参考了 [web.dev 的响应式图片指南](https://web.dev/articles/responsive-images)，再根据这幅插画的实际焦点做取舍。

## 深色不是简单反相

深色主题分别调整正文、边界和图片遮罩，而不是给整个页面套滤镜。海青在暗背景上降低饱和度，樱粉则提高明度，确保链接与焦点环仍有清楚对比。主题脚本在页面绘制前读取偏好，减少载入时的明暗闪烁。

## 留下可继续修改的边界

最后，我用三条问题检查每个决定：

- 它是否直接帮助阅读，而不是只在截图里显得热闹；
- 它是否能在手机、键盘操作和减弱动态模式中成立；
- 它是否允许未来替换内容，而不必重做整个页面。

网络小屋不需要一次装修完毕。只要结构稳定、素材来源清楚、装饰知道退后，新的文章来到时就总能找到合适的位置。
', '2026-07-04T00:00:00.000Z', NULL, 0, '开发', '["Astro","设计系统","响应式设计"]', NULL, NULL, 1, '博客开发笔记', NULL);
INSERT INTO posts (id, slug, title, description, body, published_at, updated_at, draft, category, tags_json, cover, cover_alt, featured, series, canonical_url) VALUES ('seed-post-css-motion-notes', 'css-motion-notes', '克制的网页动画：让界面呼吸而不打扰', '从动效目的、幅度与减弱模式出发，整理一套安静而可访问的 CSS 动画原则。', '
动效很容易成为页面上声音最大的人。按钮漂浮、卡片弹跳、背景不断缩放，单独看都很精致，叠在一起却会抢走正文的注意力。我为这个演示博客制定的原则是：动画只解释状态、提示方向或营造极轻的环境感；如果移除后信息仍完整，就必须允许它安静退场。文中的持续时间与位移是**界面演示参数**，不是适用于所有产品的固定标准。

## 先问它为何移动

每加一个动画，我会先写下目的，再决定属性：

- 导航抽屉需要说明“从哪里出现”，因此使用短距离位移和透明度；
- 按钮悬停只确认可交互，颜色变化比放大更稳定；
- 花瓣属于装饰，频率要低，也不能遮住链接或正文；
- 阅读进度反映真实状态，不额外添加回弹效果。

若一句话说不清目的，这段动画多半可以删除。尤其避免让大面积图片持续缩放，因为它既干扰阅读，也可能放大裁切问题。

## 小幅度与统一节奏

界面反馈通常控制在一百五十到二百四十毫秒，位移保持在数个像素。不同组件共用少量时间变量，页面就不会像由几套节拍拼在一起。下面是本站按钮反馈的简化示例：

```css
.action {
  transition: color 180ms ease, transform 180ms ease;
}

.action:hover {
  transform: translateY(-2px);
}

@media (prefers-reduced-motion: reduce) {
  .action { transition: none; }
  .action:hover { transform: none; }
}
```

## 把“减弱动态”当作完整状态

`prefers-reduced-motion` 不只是把时长调短。持续飘动、自动打字与平滑滚动应直接停止，状态变化则保留即时反馈。更多行为差异可查阅 [MDN 的减少动态媒体特性说明](https://developer.mozilla.org/zh-CN/docs/Web/CSS/@media/prefers-reduced-motion)。实现后还要用系统设置实际切换一次，确认内容不会依赖动画结束才出现。

## 最后的检查

我会依次用键盘、触屏和减弱动态模式浏览页面，观察焦点是否清楚、元素是否位移到邻近文字上方、动画是否导致布局抖动。克制并不等于完全静止，而是让移动有来由、有边界，也知道何时停下。当读者只感到界面自然，却不必意识到每一段过渡时，动效才真正完成了工作。
', '2026-07-08T00:00:00.000Z', NULL, 0, '开发', '["CSS","动效","可访问性"]', NULL, NULL, 0, '博客开发笔记', NULL);
INSERT INTO posts (id, slug, title, description, body, published_at, updated_at, draft, category, tags_json, cover, cover_alt, featured, series, canonical_url) VALUES ('seed-post-quiet-weekend', 'quiet-weekend', '一个安静周末的光影与歌单', '在一段虚构的周末记录里，收集房间光线、散步声音与适合慢慢播放的歌。', '
这是一篇为博客展示准备的**虚构周末记录**：地点、曲名与时间都只是样例，没有对应真实人物或私人行程。它想呈现的是一种很普通的节奏——不赶去完成清单，也不急着把休息变成成果，只认真感受一天怎样从窗边经过。

## 上午九点，光落在桌面

雨在清晨停了，云层仍然很厚。桌上的玻璃杯把一小块光折到墙上，随着太阳缓慢移动。我煮了淡一些的咖啡，把手机留在另一个房间，只带一本读到一半的散文集坐到窗边。读累了就看楼下晾衣绳摇动，没有拍照，也没有给这一刻配一句适合发布的话。

这种空白并不无聊。平日里被通知切碎的注意力重新连在一起，连翻页声都显得清晰。到了中午，我只记下三行：光从灰白变成温暖的金色；咖啡凉得比预想快；今天不需要证明时间被“有效利用”。

## 下午的短途散步

我沿着河岸走了一小圈，给自己一个很简单的观察任务：寻找三种不同的绿色。最后看到的是雨后苔藓、旧栏杆旁的藤叶，以及便利店门口被灯光照亮的盆栽。途中没有特别的事件，只有自行车铃、鞋底擦过湿地的声音，还有远处断断续续的练琴声。

## 夜晚歌单

下面的曲目名称同样是虚构示例，顺序按情绪而不是风格排列：

1. 《雨停后的站台》——适合整理桌面时播放；
2. 《蓝色窗帘》——把音量调低，留一点空间给环境声；
3. 《晚风把灯吹亮》——在睡前结束，不开启自动续播。

寻找可自由收听的真实录音时，我偶尔会浏览 [Internet Archive 音频馆藏](https://archive.org/details/audio)，并在使用前核对每条内容的授权说明。歌单的意义不是塞满整个晚上，而是给一天划出柔和的段落。

## 周末留下了什么

回看这一天，最喜欢的并非完成了多少事，而是重新注意到光线有速度、安静也有层次。下周依旧会忙起来，但我想保留一个小习惯：每到周末，至少让一顿饭、一段路或一首歌不被通知打断。生活未必因此改变，却会多出一块能够好好呼吸的地方。
', '2026-07-10T00:00:00.000Z', NULL, 0, '生活', '["日常","音乐","光影"]', NULL, NULL, 0, NULL, NULL);
INSERT INTO posts (id, slug, title, description, body, published_at, updated_at, draft, category, tags_json, cover, cover_alt, featured, series, canonical_url) VALUES ('seed-post-reading-workflow', 'reading-workflow', '我的长文阅读与摘录流程', '用问题、边注与回访整理长文，让摘录从句子仓库变成可继续思考的线索。', '
以前读长文，我会把漂亮句子全部划下来。文章结束时页面五颜六色，真正能复述的观点却很少。现在我把阅读分成“带着问题进入、用自己的话离开、隔一段时间回访”三个阶段。本文出现的文章标题与摘录都是为本站制作的**虚构示例**，不会冒充真实出版物或作者原话。

## 阅读前只写一个问题

开始前，我先看标题、小标题与结尾，用一句话写下此刻最想知道什么。例如阅读虚构文章《城市夜色如何改变我们的步行》时，问题不是宽泛的“作者说了什么”，而是“光线怎样影响人选择回家的路线”。问题像一根细线，能帮助我区分核心论证与有趣但暂时无关的枝节。

第一遍尽量连续读，不急着查每个陌生概念。只在段旁留下三种符号：`?` 表示需要核对，`!` 表示改变了原有看法，`→` 表示能与其他笔记连接。符号很少，注意力才不会不断离开正文。

## 摘录必须配一条边注

第二遍才整理内容，每条摘录都附上自己的回应：

- **作者主张什么**：压缩成不超过两句话；
- **证据是什么**：区分数据、案例与个人判断；
- **我为何保留它**：写出同意、怀疑或可应用的场景；
- **下一步查什么**：记录关键词，而不是立刻打开十个标签页。

示例摘录“灯光让道路显得更短”旁边，我会注明“这是感受描述，仍需寻找路线选择研究”，而不是直接把它当成结论。需要管理来源时可参考 [Zotero 文档](https://www.zotero.org/support/)，但工具只负责保存出处，理解仍要靠自己的转述。

## 二十四小时后写摘要

隔天不看原文，先凭记忆写一百字摘要，再回去检查遗漏与误解。若完全想不起某段，即使当时画了重点，也说明它还没有进入知识结构。之后我会在一周和一个月时各回访一次，只保留仍能回答最初问题的笔记。

这套流程读得更慢，却减少了“收藏等于读过”的错觉。最后留下的不是一仓库孤立金句，而是一组带出处、带判断、还能继续追问的线索。数量变少以后，反而更容易在写作或生活中真正用到它们。
', '2026-07-06T00:00:00.000Z', NULL, 0, '阅读', '["阅读","笔记","工作流"]', NULL, NULL, 0, '阅读练习', NULL);
INSERT INTO posts (id, slug, title, description, body, published_at, updated_at, draft, category, tags_json, cover, cover_alt, featured, series, canonical_url) VALUES ('seed-post-summer-anime-notes', 'summer-anime-notes', '七月动画随记：把喜欢的片段留住', '用三段虚构的夏日动画记忆，练习记录画面、声音与观看时的心情。', '
七月的晚上总有一点舍不得立刻关灯。风扇转得很慢，窗外的蝉声隔着玻璃变成柔软的底噪，我便在片尾曲结束后多坐几分钟，把刚才打动我的东西写下来。本文中的片名、人物与播出信息都是为本站排版准备的**虚构示例**，不对应真实作品；真正想保存的，是观看时那一瞬间的感受。

## 三个想要重看的片段

- 《潮汐邮局》里，见习邮差把没有地址的信放进蓝色铁盒。镜头没有解释收件人，只让海水映在她的袖口上。那份克制比对白更长久。
- 《夜行巴士的最后一站》把整段告别藏在报站声里。两个人谈论明天的天气，却始终没有说出“再见”，车窗上的倒影替他们完成了表情。
- 《玻璃温室》最安静的一幕只有浇水声。主角终于接受花期会结束，也明白照料并不是把一切永远留在原处。

## 我怎样做观看笔记

我不再逐集复述情节，而是固定记三件事：一个画面、一种声音、一个当时冒出的念头。这样写出来的文字很短，却能在几个月后把记忆重新点亮。遇到想查的制作人员，我会先把问题留在条目旁，再去 [AniList](https://anilist.co/) 等资料站核对；没有确认的信息就不写成事实。

列表也不按“好看”或“不好看”排序。我更在意作品是否给生活留下了一点回声：也许是开始观察傍晚云层的颜色，也许是愿意给久未联系的人写一封信。评分很快会模糊，具体的变化却值得保存。

## 留一点空白

随记不是评测，也不必替每个感受找出结论。下一次重看时，我可能会推翻今天的理解，那正是记录有趣的地方。先把片段轻轻放进文字里，像夹在书页间的一张车票；等季节过去，再回来看看自己当时为何停下目光。
', '2026-07-14T00:00:00.000Z', '2026-07-15T00:00:00.000Z', 0, '动画', '["动画","随记","观看记录"]', NULL, NULL, 1, '七月随记', NULL);
INSERT INTO projects (id, slug, title, description, body, project_date, status, tags_json, cover, repository_url, demo_url, featured, sort_order) VALUES ('seed-project-anime-watchlist', 'anime-watchlist', 'Anime Watchlist', '按观看状态、季节与个人笔记整理动画条目的轻量清单概念。', '
这是用于展示项目页面结构的**虚构示例项目**。条目名称、进度与功能描述只服务于界面演示，目前没有公开仓库或在线体验地址，因此 frontmatter 中没有填写相应链接。

## 想解决的问题

普通待办清单很难保存“为什么想看”和“看完留下了什么”。这个概念把每部动画拆成观看状态、季度、主题标签和一句私人备注，让清单既能规划，也能在完结后成为简短档案。

## 当前进度

- 已完成条目模型与三种状态筛选；
- 正在整理键盘操作和空列表提示；
- 后续将验证移动端长标题与多标签的显示效果。

所有演示条目均使用虚构片名，不会混入真实评分或冒充正式作品资料。
', '2026-07-13T00:00:00.000Z', 'active', '["动画","内容整理","Astro"]', NULL, NULL, NULL, 1, 0);
INSERT INTO projects (id, slug, title, description, body, project_date, status, tags_json, cover, repository_url, demo_url, featured, sort_order) VALUES ('seed-project-photo-notes', 'photo-notes', 'Photo Notes', '围绕光线、色彩与拍摄缘由编排的一组虚构照片笔记样例。', '
Photo Notes 是一个已经完成的**虚构展示项目**，用于示范已完成状态、项目正文与标签的呈现。页面没有绑定真实相册、人物资料、代码仓库或演示地址，文中照片名称也都是占位样例。

## 完成内容

- 以“清晨、雨后、夜色”三个主题组织图文；
- 每张照片配一段拍摄意图，而不是器材参数堆叠；
- 为图片预留稳定比例与替代文字位置；
- 在窄屏上保持说明文字与图片顺序清楚。

项目最终保留十二条示例笔记，并加入素材来源检查清单。它更像一本安静的小册子，而不是追求无限滚动的图片瀑布流。
', '2026-06-28T00:00:00.000Z', 'completed', '["摄影","视觉记录","静态页面"]', NULL, NULL, NULL, 0, 1);
INSERT INTO projects (id, slug, title, description, body, project_date, status, tags_json, cover, repository_url, demo_url, featured, sort_order) VALUES ('seed-project-zhaozhao-blog', 'zhaozhao-blog', '233昭 Blog', '以 Astro 构建的浅色动画气质个人博客演示，专注阅读、发现与可维护写作。', '
233昭 Blog 是本站自身的**演示项目记录**。社交信息和文章内容均可替换，当前进度描述用于呈现项目详情页，不代表公开产品承诺。项目尚未提供独立仓库或部署演示链接，因此相关可选字段保持省略。

## 项目方向

网站采用 Astro SSR 与运行时 Markdown 内容仓库，围绕文章、分类标签、归档和项目建立清楚的浏览路径。视觉使用中性色作为基础，以海青和樱粉点出状态；插画保留完整构图，装饰动效遵循系统的减弱动态偏好。

## 正在推进

- 完善文章详情、搜索和相关文章发现；
- 检查键盘导航、焦点管理与深浅主题对比；
- 验证手机、平板与宽屏下的排版边界；
- 为示例素材保留明确来源与替换说明。

项目的完成标准不是组件数量，而是内容换成另一位作者的资料后，结构依旧清楚、链接依旧可靠、阅读仍然安静。
', '2026-07-15T00:00:00.000Z', 'active', '["Astro","TypeScript","博客","可访问性"]', NULL, NULL, NULL, 1, 2);
