/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: 4b0584090477cbac9b3b1d7cee5d07fd)
interface __BaseEnv_Env {
	MEDIA: KVNamespace;
	DB: D1Database;
	ASSETS: Fetcher;
	PUBLIC_SITE_URL: string;
	LEGACY_SITE_URL: string;
	PUBLIC_GISCUS_REPO: string;
	PUBLIC_GISCUS_REPO_ID: string;
	PUBLIC_GISCUS_CATEGORY: string;
	PUBLIC_GISCUS_CATEGORY_ID: string;
	ADMIN_PASSWORD: string;
	ADMIN_SESSION_SECRET: string;
	PUBLIC_TURNSTILE_SITE_KEY: string;
	HTML_CACHE_DISABLED: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PUBLIC_SITE_URL" | "LEGACY_SITE_URL" | "PUBLIC_GISCUS_REPO" | "PUBLIC_GISCUS_REPO_ID" | "PUBLIC_GISCUS_CATEGORY" | "PUBLIC_GISCUS_CATEGORY_ID" | "ADMIN_PASSWORD" | "ADMIN_SESSION_SECRET" | "PUBLIC_TURNSTILE_SITE_KEY" | "HTML_CACHE_DISABLED">> {}
}
