/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: 4f4f060cbddbe56a075ecdbbe5b63486)
interface __BaseEnv_Env {
	MEDIA: R2Bucket;
	DB: D1Database;
	ASSETS: Fetcher;
	PUBLIC_SITE_URL: string;
	PUBLIC_GISCUS_REPO: string;
	PUBLIC_GISCUS_REPO_ID: string;
	PUBLIC_GISCUS_CATEGORY: string;
	PUBLIC_GISCUS_CATEGORY_ID: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PUBLIC_SITE_URL" | "PUBLIC_GISCUS_REPO" | "PUBLIC_GISCUS_REPO_ID" | "PUBLIC_GISCUS_CATEGORY" | "PUBLIC_GISCUS_CATEGORY_ID">> {}
}
